org: minhthong
app: users-api
service: users-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: Allow
          Principal: "*"
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - s3:* 
          Resource: "*"
  stage: dev
  
functions:
  ${file(src/functions/users/routing.yml)}

custom:
  serverless-offline:
    httpPort: 5000
    stageVariables:
      foo: "bar"

plugins:
  - serverless-plugin-typescript
  - serverless-offline