list:
  handler: src/functions/users/handler.gets
  events:
    - http:
        path: /user
        method: get
findById:
  handler: src/functions/users/handler.findOne
  events:
    - http:
        path: /user/{id}
        method: get
create:
  handler: src/functions/users/handler.createUser
  events:
    - http:
        path: /user
        method: post
update:
  handler: src/functions/users/handler.updateUser
  events:
    - http:
        path: /user/{id}
        method: put
delete:
  handler: src/functions/users/handler.deleteUser
  events:
    - http:
        path: /user/{id}
        method: delete